# ansible n1 -m file -a "path=/home/centos/n1_dir state=directory"
---
- name: Update n1 server
  hosts: n1
  

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir_
      state: directory
  - name: Create Directory
    file:
      path: /home/centos/new_dir_1
      state: directory


- name: Update n2 server
  hosts: n2
  

  - name: Create Directory
    file:
      path: /home/centos/new_dir_1
      state: directory
  - name: Create Directory
    file:
      path: /home/centos/new_dir_2
      state: directory

  tasks:
    - name: Update group1 server
  hosts: g1
  

  tasks:
  
  - name: Create Directory
    file:
      path: /home/centos/new_dir_group1
      state: directory

 - name: Create Directory
    file:
      path: /home/centos/new_dir_group2
      state: directory


    file:
      path: /home/centos/new_dir_group1
      state: directory

...
