---
- name: Configure EC2 for Flask app
  hosts: n3
  tasks:
    - name: install python3 and pip package manager
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      loop:
        - python3
        - python3-pip
        - nginx
    - name: Install Flask and wsgi for it
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - flask
        - gunicorn3
   

...
