---
- name: install python3
  hosts: n3
  become: yes

  tasks:
  - name: install python3
    apt:
      name: python3
      state: present
  
  - name: install pip package manager
    apt:
      name: pip package manager
      state: present
...
