---
- name: Configure EC2 for Flask app
  hosts: n3
  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: true
  - name: Upgrade all apt packages
    apt: upgrade=yes force_apt_get=yes
    become: true
  - name: install python3 and pip package manager
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      loop:
        - python3
        - python3-pip
        - nginx
    - name: Install Flask and wsgi for it
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - flask
        - gunicorn3
   

...
