---
- name: install python3
  hosts: n3
  become: yes

  tasks:
- name: install python3
    apt:
    packages:   
     - python3.8-venv
     - Python3-pip
     - python3-dev
     - nginx
    state: present
...
